# Generated by Django 4.1.5 on 2023-01-31 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
